version: 2

node-image: &node-image
  image: circleci/node:6

set-npm-global: &set-npm-global
  run:
    name: set-npm-global
    command: |
      mkdir -p ~/.npm-global
      npm config set prefix '~/.npm-global'
      echo 'export NPM_CONFIG_PREFIX=~/.npm-global' >> $BASH_ENV
      echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      source $BASH_ENV

save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      - ".git"
      - "~/.npm-global"

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

jobs:
  install:
    docker:
      - <<: *node-image
    steps:
      - checkout
      - <<: *set-npm-global
      - run: npm install -g npm@6.1.0
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-greenkeeper
          command: |
            npm install -g greenkeeper-lockfile
            greenkeeper-lockfile-update
      - run: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - <<: *save
  lint:
    docker:
      - <<: *node-image
    steps:
      - <<: *restore
      - run: npm run lint
  test:
    docker:
      - <<: *node-image
    steps:
      - <<: *restore
      - run: npm test
  test-pg:
    docker:
      - <<: *node-image
        environment:
          - DATABASE_URL=postgres://ubuntu@localhost:5432/circle_test
      - image: postgres:10.4-alpine
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=circle_test
    steps:
      - <<: *restore
      - run:
          name: test
          command: npm run migrate up -- -m test/migrations && npm run migrate down 0 -- -m test/migrations --timestamps
  test-cocroach:
    docker:
      - <<: *node-image
        environment:
          - DATABASE_URL=postgresql://root@localhost:26257/circle_test
      - image: cockroachdb/cockroach:v1.1.8
        command: ['start', '--insecure', '--host=localhost']
    steps:
      - <<: *restore
      - run:
          name: create-cockroach-db
          command: node -e '(new require("pg").Pool({connectionString:process.env.DATABASE_URL})).query("CREATE DATABASE circle_test").then(function(){process.exit(0)})'
      - run:
          name: test
          command: npm run migrate up -- -m test/cockroach -s '' --migrations-schema circle_test --no-lock && npm run migrate down 0 -- -m test/cockroach -s '' --migrations-schema circle_test --no-lock --timestamps
  finish:
    docker:
      - <<: *node-image
    steps:
      - <<: *restore
      - <<: *set-npm-global
      - run: greenkeeper-lockfile-upload

workflows:
  version: 2
  main_workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - test-pg:
          requires:
            - install
      - test-cocroach:
          requires:
            - install
      - finish:
          requires:
            - lint
            - test
            - test-pg
            - test-cocroach
