version: 2
jobs:
   build:
     docker:
       - image: circleci/node:4.8.2
         environment:
         - NODE_ENV=test
         - DATABASE_URL_POSTGRES=postgres://ubuntu@localhost:5432/circle_test
         - DATABASE_URL_COCKROACH=postgresql://root@localhost:26257/circle_test
       - image: postgres:9.6
         environment:
         - POSTGRES_USER=ubuntu
         - POSTGRES_DB=circle_test
       - image: cockroachdb/cockroach:v1.1.6
         command: ['start', '--insecure', '--host=localhost']
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@5.8.0'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm
          command: npm ci
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: lint
          command: npm run lint
       - run:
          name: create-cockroach-db
          command: node -e '(new require("pg").Pool({connectionString:process.env.DATABASE_URL_COCKROACH})).query("CREATE DATABASE circle_test").then(function(){process.exit(0)})'
       - run:
          name: test
          command: npm test
