version: 2
jobs:
   build:
     docker:
       - image: circleci/node:4.8.2
         environment:
         - NODE_ENV=test
         - DATABASE_URL=postgres://ubuntu@localhost:5432/circle_test
       - image: postgres:9.6
         environment:
         - POSTGRES_USER=ubuntu
         - POSTGRES_DB=circle_test
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm
          command: npm ci
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: lint
          command: npm run lint
       - run:
          name: test
          command: npm test
