version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6
         environment:
         - NODE_ENV=test
         - DATABASE_URL_POSTGRES=postgres://ubuntu@localhost:5432/circle_test
         - DATABASE_URL_COCKROACH=postgresql://root@localhost:26257/circle_test
       - image: postgres:10.4-alpine
         environment:
         - POSTGRES_USER=ubuntu
         - POSTGRES_DB=circle_test
       - image: cockroachdb/cockroach:v1.1.8
         command: ['start', '--insecure', '--host=localhost']
     steps:
       - checkout
       - run:
          name: update-npm
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export NPM_CONFIG_PREFIX=~/.npm-global' >> $BASH_ENV
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            npm install -g npm@6.1.0
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm
          command: npm ci
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: lint
          command: npm run lint
       - run:
          name: create-cockroach-db
          command: node -e '(new require("pg").Pool({connectionString:process.env.DATABASE_URL_COCKROACH})).query("CREATE DATABASE circle_test").then(function(){process.exit(0)})'
       - run:
          name: test
          command: npm test
